# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gotermsql < Formula
  desc "A terminal SQL IDE supporting PostgreSQL, MySQL, SQLite, and DuckDB"
  homepage "https://github.com/sadopc/gotermsql"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sadopc/gotermsql/releases/download/v0.1.0/gotermsql_0.1.0_darwin_amd64.tar.gz"
      sha256 "378068df0933d52096d9237cbe2129a064d70ca2811882ed7103762308879cbc"

      def install
        bin.install "gotermsql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sadopc/gotermsql/releases/download/v0.1.0/gotermsql_0.1.0_darwin_arm64.tar.gz"
      sha256 "84b6cd5c6c764d878feeecc95a6edaa7331ba06c765ca1289cd1b445d51ed145"

      def install
        bin.install "gotermsql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sadopc/gotermsql/releases/download/v0.1.0/gotermsql_0.1.0_linux_amd64.tar.gz"
      sha256 "b06cce13326eb8a9cd92fdb755894acf80454d7a716f4292f46a31a94d7a486b"
      def install
        bin.install "gotermsql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sadopc/gotermsql/releases/download/v0.1.0/gotermsql_0.1.0_linux_arm64.tar.gz"
      sha256 "1520c3c63352980eb48cf3f4ca80a4c3010cf9f992cb88b05fe48066db060ea7"
      def install
        bin.install "gotermsql"
      end
    end
  end

  test do
    system "#{bin}/gotermsql", "version"
  end
end
